project:
  type: book
  output-dir: docs

book:
  title: "Heredity"
  favicon: gene.png
  author: "Aj!"
  date: "5/28/2023"
  chapters:
    - index.qmd
    - i_interplay.qmd
    - i_analogies.qmd
    - i_assumptions.qmd
    - i_historical.qmd
    
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly

  pdf:
    documentclass: scrreprt



