project:
  type: book
  output-dir: docs

book:
  title: "Heredity"
  favicon: bulb.png
  author: "Aj!"
  date: "5/28/2023"
  chapters:
    - index.qmd
    - interplay.qmd
    - analogies.qmd
    - historical.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly

  pdf:
    documentclass: scrreprt



