# Supposed Historical Problems

## BUT Galton ignored possible environmental factors for the children of eminent people to be eminent as well. 

Galton specifically avoids this: in the beginning of Hereditary Genius he writes: “I must not compare the sons of eminent men with those of non-eminent, because much of which I should ascribe to breed, others might ascribe to parental encouragement and example” [@galton1891 p.37]. It was precisely for this reason that he undertook to compare the proportion of eminent people among the biological children of eminent people with adopted sons of Popes and other dignitaries of the Roman Catholic Church, in the attempt to disentangle possibly confounding influences from heredity and environment. In his own words: “If social help is really of the highest importance, the nephews [adopted children] of the Popes will attain eminence as frequently, or nearly so, as the sons of other eminent men; otherwise, they will not” [@galton1891 p.42]. And the data clearly indicated a significant difference between the two groups, leading Galton to conclude that the environmental explanation could not be the whole story. This does not prove that Galton was right, of course, but it does show that his argument was immensely more sophisticated than Moore pictured it.

BUT Galton never pointed out that more than half his “geniuses” turned up in families with no history of distinction at all. 
Galton did point out that among poets, musicians, painters, divines, and scholars, more than half of the illustrious men came from families with no history of distinction [@galton1891 p. 228,239,249,274,283,300]. This methodological criticism is both factually incorrect and entirely irrelevant. First, Furthermore, summing up the information for all the professions that he considered, Galton concluded from his tabulated data that, cumulatively, “exactly one-half of the illustrious men have one or more eminent relations” [@galton1891 p. 322],from which it deductively follows that one-half of the illustrious men did not have any eminent relations. Second, it is unclear why Jones thinks that the fact of more than half of geniuses turning up in families with no distinction would create a problem for Galton’s hereditarianism. Since Galton’s illustrious men were selected in such a way that their ratio to the general population was 1 to 4,000, the hereditarian explanation could easily accommodate the proportion of eminent people from no-distinction families significantly higher than 50 percent.

## BUT Ronald A. Fisher once called heritability “one of those unfortunate shortcuts, which have often emerged in biometry for lack of a more thorough analysis of the data” [@fisher1951 p.217].

 - First, Fisher’s paper addressed issues connected with animal breeding problems. Fisher’s argument seems to be an inappropriate instrument for their human behavioral genetics.^[ If critics are happy to concede that heritability works fine in experimental studies of animals, Fisher’s paper is inappropriate and wrong.]

 - Second, Fisher happily used heritability in his book, “The Genetical Theory of Natural Selection” where he talks about “the fraction of the total observable variance of the measurement, which may be regarded as genetic variance” [@fisher1930 p.33]. He left that part unchanged in the significantly revised second edition of 1958. Many times, he additionally talked about heritable variation [@fisher1983 p.140], about the genetic component of variance vs. total phenotypic variance [@fisher1983 p.228]. Elsewhere, again, Fisher praised Galton for trying to give numerical precision to concepts like “the strength of inheritance”, or heritability. [@fisher1959 p.2]

 - Third, Fisher’s disparaging comment about heritability was far from being universally accepted. His worry was mainly about the heritability value being under undue influences of measurement error and changes in population parameters. For instance, his view was criticized by Johansson for “missing the important point that for practical breeding work we need estimates of heritability that are valid under the conditions where they will be applied” [@johansson1961 p.9].

 - Fourth, Fisher’s grounds for dissatisfaction with heritability were completely different from the reasons of the critics who quote him in support of their own views. In the opinion of most of the authors who cite Fisher, one of the main problems with heritability is that genetic variance (the numerator) cannot be determined because of the confounding influence of gene–environment interaction. But Fisher himself had nothing but contempt for this kind of criticism, as seen from his letter to the son of Charles Darwin in 1935: “There is one point in which Hogben and his associates are riding for a fall, and that is in making a great song about the possible, but unproved, importance of non-linear interactions between hereditary and environmental factors. J. B. S. Haldane seems tempted to join in this” [@fisher1983 p.260]. It is rather funny that contemporary critics of heritability (some of them doing research in history of biology!) press the interaction objection, which Lewontin basically took over from [@hogben1933], and then even present Fisher as their ally in this. By the way, Fisher’s judgment that Haldane “seems tempted to join in this” proved correct. Haldane’s book in which he defended Hogben’s position on interactions soon followed [@haldane2016].

 - Fifth, while there is nothing wrong with these authors trying to support their opposition to human behavior genetics by relying on Fisher as a supreme authority in genetics (after all, he was one of the architects of the Modern Synthesis), they should be aware that they might not find his other views about genetics so appealing. Some of them would probably be shocked to know that, despite his derogatory aside about heritability, Fisher actually believed that genetics supports the heritability of racial differences in intelligence. At about the same time that he wrote the article they quote, he suggested the following formulation for the UNESCO statement on race: “Available scientific knowledge provides a firm basis for believing that the groups of mankind differ in their innate capacity for intellectual and emotional development, seeing that such groups differ undoubtedly in a very large number of their genes” [quoted in @provine1986 p. 875 – italics added]. This shows that one should be careful in choosing one’s authorities because they can force one to go in an unwanted direction.

## BUT Morton mismeasured skulls

Gould uses his expertise in biology to claim that Morton had bias and mismeasured a set of skulls to  conclude craniometric differences between ancestral populations. The set of 201 skulls from the Morton collection were re-examined in 1986 by John S. Michael in which the results were presented in a paper published in Current Anthropology. [@michael1988] Michael found that the differences reported by Morton were basically corroborated by his remeasurements. Michaels strongly outlines his scientific and philosophical differences with Morton but concludes that he could find no indication of the systematic bias that Gould ascribed to Morton, and that in his opinion, “Morton’s research was conducted with integrity” [@michael1988 p.353]. 

Morton’s discovery is accepted today in standard reference books [see @sternberg1982 p. 773; @brody1992 p. 301; @mackintosh2011 p.184], and even by mainstream environmentarians like Ulric Neisser. As a responsible psychologist who knows that this kind of dispute is ultimately resolved by empirical verification, he had no other choice but to concede that with respect to the racial differences in the mean measured sizes of skulls and brains, “there is indeed a small overall trend in the direction [Lynn and Rushton] describe” [@neisser1997 p.80]^[ Neisser (one of the leading critics of the genetic hypothesis and the chair of the American Psychological Association Task Force that prepared the report “Intelligence: Knowns and Unknowns”) did not hide his strong aversion to the hereditarian views of J. Philippe Rushton when he said: “I do not have the space or the stomach to reply to all the points raised by Rushton” 
]

## BUT Burt faked twin data
(revise later)

There is no consensus that Burt faked twin data. Several books have inquired into the topic and have concluded that the fraud theory does not have any conclusive amount of evidence [@joynson1989; @fancher1991]. In a detailed analysis of the topic by Nicholas Mackintosh, he concluded: “If the MZ twin data were the only grounds for accusing Burt of fraud, one would probably have to give him the benefit of the doubt” [@mackintosh1995 p.68]. 

Every study performed between 1981 and 1997 on twins reared apart has had a correlation between 60 percent and 80 percent in which larger studies have had larger reported correlations [@devlin1997].

## BUT Burt’s theories led to the eleven plus exams^[11+ exams often involved an IQ test, where the purpose was to select the most academically able children, who would then be accepted by schools with more demanding educational programs.]

Britain’s notorious “11+ examination” was not a creation of psychometricians led by Cyril Burt; it developed slowly out of the “free place examination” for grammar school scholarships, instituted before any IQ tests existed. The testers’ growing influence produced the eventual inclusion of an IQ test and a new rationale for 11+, but not the examination itself or its social functions. [@samelson1982 p.656]

@mackintosh1995 states, "Whatever Gould ... or Kamin ... may say, Burt was certainly not responsible for the institution of the 11+ exam in English schools after the 1944 Education Act, let alone for the practice of selection for “free places” in secondary schools in the 1920s and 1930s. Selection was already built into the system: the only question at issue was the basis on which it was to occur."

IQ tests were thus not used to establish a system of selective secondary education. That system was already in effect. [@mackintosh2011 p.24]
