
# Laws and Findings of Behavioral Genetics

## Four Laws of Behavioral Genetics

@turkheimer2000 lays out three laws of behavioral genetics, each about the three types of measurable phenotypic variation in family studies: genetic, shared-environmental, and non-shared environemntal variation.

 - All human behavioral traits are heritable. [That is, they are affected to some degree by genetic variation.]
    
 - The effect of being raised in the same family is smaller than the effect of genes.
 
 - A substantial portion of the variation in complex human behavioural traits is not accounted for by the effects of genes or families

A fourth law has been proposed by @chabris2015 stating:

 - A typical human behavioral trait is associated with very many genetic variants, each of which accounts for a very small percentage of the behavioral variability.

Each of these laws are documented more in depth below in @plomin2016.

## Ten Replicated Findings of Behavioral Genetics

Most of this information comes from @plomin2016.^[Explained here in a simple way https://tagc.world/10-robust-things-we-know-about-genes-environments-and-behaviour/
https://pamojaeducation.com/blog/for-those-of-you-who-like-biology-some-behavioural-genetics
]

### 1- All psychological traits show significant and substantial genetic influence
All traits, including psychological traits, are heritable.This has led this to be described as the first ‘law’ of behavioral genetics [@turkheimer2000]. Traits in psychological domains have consistently shown significant genetic influence. [@plomin2008]. @polderman2015 systematically categorized and meta-analyzed all prior twin studies. When investigating cognitive, psychiatric, and neurological traits with enough data to have a provided heritability estimate, the heritability estimate for these traits average around a little less than fifty percent. Between cognitive traits, the lowest and highest heritabilities were 0.19 and 0.67. Between neurological traits, the lowest and highest heritabilities were 0.31 to 0.51. Between psychiatric traits, the lowest and highest heritabilities were 0.32 and 0.74. 

The research for genetic attribution has primarily relied on the twin design that compares resemblance of identical and fraternal twins and the adoption design that compares resemblance of relatives separated by adoption. Although the twin and adoption designs have separately been criticized [@plomin2008], these two designs generally converge on the same conclusion, despite making very different assumptions, which adds strength to these conclusions. 

Genome-wide Complex Trait Analysis [@yang2011]. uses hundreds of thousands of DNA differences across the genome to estimate chance genetic similarity for each pair of individuals in a large sample of conventionally unrelated individuals and to relate this chance genetic similarity to phenotypic similarity. GCTA underestimates genetic influence for several reasons and requires samples of several thousand individuals in order to pick up the tiny signal of chance genetic similarity from the noise of DNA differences across the genome [@vinkhuyzen2013]. Nonetheless, GCTA has consistently yielded evidence for significant genetic influence for 

 - **cognitive abilities** [@benyamin2013; @davies2015; @stpourcain2014] 
 
 - **psychopathology** [@davis2013; @gaugler2014; @klei2012; @lubke2012; @lubke2013; @mcgue2013; @ripke2013; @wray2014]

 - **personality** [@rietveld2013; @verweij2012; @vinkhuyzen2012]

 - **substance use/drug dependence** [@palmer2014; @vrieze2013]

thus supporting the results of twin and adoption studies.

"*Significant and substantial genetic influence on individual differences in psychological traits is so widespread that we are unable to name an exception. The challenge now is to find any reliably measured behavioral trait for which genetic influence is not significantly different from zero in more than one adequately powered study.*" 

### 2- No traits are 100% heritable

No traits are 100% heritable [@plomin1989; @turkheimer2000]. Although heritability estimates are significantly greater than 0%, they are also significantly less than 100%. While there are virtually no traits that are 100 percent heritable, we must note that behavioral traits are less reliably measured than physical traits such as height and error of measurement contributes to non-heritable variance. 

### 3- Heritability is caused by many genes of small effect

A typical human behavioral trait is associated with very many genetic variants, each of which accounts for a very small percentage of the behavioral variability. This has been called the fourth law of behavioral genetics [@chabris2015]. GCTA also provides evidence for the highly polygenic nature of quantitative traits and qualitative disorders because it shows that SNPs on each chromosome contribute cumulatively to the heritability estimated by GCTA [@yang2013],  The strongest evidence comes from a method called genome-wide association (GWA), which has been widely used in attempts to identify specific DNA associations with quantitative traits and qualitative disorders [@manolio2009]. 

GWA has been successful in detecting SNP associations for many traits and disorders [@visscher2012], but it was a shock to discover that the largest effect sizes are extremely small [@gratten2014]. In other words, the largest effect sizes detected by GWA are extremely small for both disorders and traits. This finding has been noted by many others, and specifically in relation to psychological traits [e.g. @gratten2014; @plomin2014].

Although the power of GWA is limited to detect such minuscule effects even with samples in the tens or hundreds of thousands, these studies have tremendous power to detect larger effects [@robinson2014]. For example, a GWA study of 20,000 individuals has 99.9% power to detect an association with an effect size that accounts for 1% of the variance (i.e., a correlation of 0.10). This suggests that no such associations exist with effect sizes larger than 1% in the population. Some extremely rare mutations have large effects on individuals, but because they are rare their effect on the population is small. If the largest effects are so small, the smallest effects are likely to be infinitesimal, which implies that heritability is caused by many genes of small effect [@chabris2015; @plomin2013].

### 4- Phenotypic correlations between psychological traits show significant and substantial genetic mediation

Much psychological research is about the relationship between traits. When genetically informed designs are used for these psychological correlations, research consistently points to a finding with far-reaching implications: Phenotypic covariance between traits is significantly and substantially caused by genetic covariance, not just environmentally driven covariance. Multivariate genetic analysis estimates the extent to which genetic and environmental influences contribute to the phenotypic covariance between traits by comparing for example the cross-trait cross-twin correlations for MZ and same-sex DZ twins (i.e., correlating one twin’s X with the co-twin’s Y) [@plomin2008]. If the MZ cross-correlation is greater than the DZ cross-correlation, it suggests that genetic factors contribute to the phenotypic correlation between the traits, which is what we mean by the phrase genetic mediation.

Cognitive abilities have been studied most systematically from a multivariate genetic perspective. This research consistently shows that the phenotypic correlations among cognitive abilities are mediated significantly and substantially by genetic factors, called generalist genes [@plomin2005]. 

 - For example, [@davis2009] a multivariate genetic analysis of intelligence, reading, mathematics and language in nearly 5000 12-year-old twins found that genetic factors consistently accounted for over half of the phenotypic correlations. These findings have received support from multivariate GCTA [@trzaskowski2013]. 

More than one hundred twin studies have addressed the key question of comorbidity in psychopathology and this body of research also consistently finds substantial genetic overlap between common disorders [@cerda2009; @kendler2003] in children [@rhee2014] and in adults [@kendler2010]. 

 - For example, a review of 23 twin studies and 12 family studies confirms that anxiety and depression are correlated entirely for genetic reasons [@middeldorp2005]. These twin study findings of genetic overlap among disorders have received support from multivariate GCTA studies [@lee2013] and from GWA studies [@consortium2013].

 - For example, a recent review of molecular genetic studies of schizophrenia concluded: “There is evidence for shared genetic risk between schizophrenia, bipolar disorder, autism spectrum disorders, intellectual disability and attention-deficit and hyperactivity disorder” [@kavanagh2014]. 

These results convey an important implication: the genetic structure of psychopathology does not map neatly on current diagnostic classifications [@doherty2014]. Moreover, correlations between personality dimensions and psychopathological diagnoses are also mediated genetically, most notably between neuroticism and depression [@kendler2006].

This finding goes far beyond these well-known examples of genetic contributions to correlations in the domains of cognitive abilities and psychopathology. Whenever a phenotypic correlation is found between two behavioral traits, the genetic contribution to the phenotypic correlation is significant and substantial, with the usual caveat of adequate power, which is especially severe for low phenotypic correlations. As one of many such examples of new but as yet unreplicated findings of this type, genes accounted for more than 70% of the phenotypic correlations of about 0.30 between attitudes toward exercise and exercise behavior, meaning that many of the same genes affect the two traits [@huppertz2013].

This finding extends even further, to the phenotypic correlations between behavior and other variables that are not ostensibly measures of behavior. One of our other findings is of this type: phenotypic correlations between behavioral measures and environmental measures (Finding 8).

### 5- The heritability of intelligence increases throughout development

The heritability of intelligence increases throughout development. Although it would be reasonable to expect that experiences accumulate in their effect as time goes by, which some developmental theories propose, [e.g., @baltes1980] the heritability of intelligence has consistently over three decades’ research been found to increase linearly throughout the life course in longitudinal as well as cross-sectional analyses and in adoption as well as twin studies [@mcgue1993; @plomin1986; @plomin2014]. @haworth2009^[is an analysis of cross-sectional data for 11,000 pairs of twins, larger than all previous twin studies combined
] showed that the heritability of intelligence linearly increases from childhood to adulthood. @polderman2015 compiled all previous twin studies and found that the heritability of intelligence increases with age and the shared environmental effect decreases with age. A meta-analysis of results from longitudinal twin and adoption studies also found increases in heritability from infancy through adolescence [@briley2013]. 

Increasing heritability for intelligence is interesting because other domains such as personality do not show systematic changes in heritability during development [@turkheimer2013]; reasons for this difference in results are not known. However, a meta-analysis of seven behavioral domains other than intelligence found significant increases in heritability for externalizing and internalizing behavior problems and social attitudes during adolescence and young adulthood [@bergen2007]. 

### 6- Age-to-age stability is mainly due to genetics

Longitudinal genetic studies consistently show that phenotypic correlations from age to age are largely due to genetic stability. In other words, genetic effects contribute to continuity (the same genes affect the trait across age), whereas age-to-age change is primarily the provenance of environmental factors [@plomin1986]. Longitudinal genetic analysis is a variant on multivariate genetic analysis of the phenotypic covariance across time for the ‘same’ trait. Such research has shown that phenotypic stability from age to age is mainly due to genetics for personality, psychopathology and intelligence, domains for which the most longitudinal genetic data are available.

 - For personality, the first report of a longitudinal genetic analysis over an age span of a decade concluded that 80% of the phenotypic stability was mediated genetically [@mcgue1993b], which has been confirmed in recent meta-analyses [@briley2014; @turkheimer2013]. 

 - For psychopathology, fewer longitudinal genetic studies are available but results are similar for diverse traits related to psychopathology such as borderline personality disorder [@bornovalova2009]; antisocial personality disorder [@burt2007]; aggression [@vanbeijsterveldt2003]; attention problems [@rietveld2004]; withdrawn behavior [@hoekstra2008]; anxiety and depression [@kendler2008]; general internalizing and externalizing problems [@bartels2004].

 - For intelligence, similar results have been reported in @tuckerdrob2014. This finding creates an apparent paradox: How can the heritability of intelligence increase so substantially throughout development if genetic effects are stable? ^[That is, how can the same genes largely affect intelligence across the life course and yet genes account for more variance as time goes by?
] Increasing heritability despite genetic stability implies some contribution from what has been called genetic amplification [@plomin1985]. In other words, genetic nudges early in development are magnified as time goes by, increasing heritability, but the same genetic propensities continue to affect behavior throughout the life course. This amplification model has recently been supported in a [@briley2013]. Genotype-environment correlation seems the most likely explanation in which small genetic differences are amplified as children select, modify and create environments correlated with their genetic propensities [@scarr1983]. ^[ As mentioned earlier, all behavioral genetic results are limited by the samples, measures and methods employed, which means that such results could differ for example in different cultures.This active model of selected environments—in contrast to the traditional model of imposed environments—offers a general paradigm for thinking about how genotypes become phenotypes (Plomin, 1994). Genotype-environment correlation also predicts the next finding about genetic influence on ostensible measures of the environment.] 

### 7- Most measures of the ‘environment’ show significant genetic influence

Although it might seem a peculiar thing to do, measures of the environment widely used in psychological science – such as parenting, social support, and life events – can be treated as dependent measures in genetic analyses. If they are truly measures of the environment they should not show genetic influence.^[ How can measures of the environment show genetic influence? The reason is that such measures do not assess the environment ‘out there’ independent of the person. As noted above, we select, modify and create environments correlated with our genetic behavioral propensities such as personality and psychopathology (McAdams et al., 2013).
] However, significant genetic influence was found for objective quantifications of environments. ^[ This includes videotape observations of parenting as well as self-report measures of parenting, social support, and life events.]

In 1991, a review of the first 18 studies using environmental measures as dependent measures in genetically sensitive designs showed evidence for genetic influence for these measures of the environment [@plomin1991]. Since 1991, more than 150 papers using environmental measures in genetically sensitive designs have been published, consistently showing significant genetic influence on environmental measures, extending the findings from family environments to neighborhood, school, and work environments. A review of 55 independent genetic studies found an average heritability of 0.27 across 35 diverse environmental measures [@kendler2007] Meta-analyses of parenting, the most frequently studied domain, show genetic influence that is driven by child characteristics [@avinun2013] as well as by parent characteristics [@klahr2013]. ^[ Some exceptions have emerged. Not surprisingly, when life events are separated into uncontrollable events (e.g., death of a spouse) and controllable life events (e.g., financial problems), the former show nonsignificant genetic influence.] ^[ As a reminder that all behavioral genetic results can differ in different cultures, a comparison of parenting in Japan and Sweden found that parenting in Japan showed more genetic influence than in Sweden, which is consistent with the view that parenting is more child centered in Japan than in the West (Shikishima et al., 2012).]

GCTA has begun to replicate these findings from twin studies. For example, GCTA has shown significant genetic influence on stressful life events [@power2012] and on variables often used as environmental measures in epidemiological studies such as years of schooling [@rietveld2013]. GCTA can also circumvent a limitation of twin studies when the twins are children. Such twin studies are limited to investigating within-family (twin-specific) experiences, whereas many important environmental factors such as SES are the same for two children in a family. However, GCTA can assess genetic influence on family environments such as SES that differ between families not within families. GCTA has shown genetic influence on family SES [@trzaskowski2014] and an index of social deprivation [@marioni2014].

### 8- Most measures of the ‘environment’ show significant genetic influence

If genetic factors affect environmental measures as well as behavioral measures, it is reasonable to ask the extent to which associations between environmental measures and behavioral measures are mediated genetically. For example, rather than assuming that correlations between parenting and children’s behavior are caused by the environmental effect of parenting on children’s behavior, it is important to consider the possibility that the correlation is in part due to genetic factors that influence both parenting and children’s behavior. Individual differences in parenting might reflect genetically driven differences in children’s behavior or differences in parenting might be due to genetically driven propensities of parents that are inherited directly by their children.

In 1985, using a parent-offspring adoption design, evidence emerged for genetic mediation that accounted on average for about half of the correlations between measures of home environment and infants’ development [@plomin1985b]. For example, at age 2, the correlation between the Home Observation for Measurement of the Environment (HOME) and Bayley Mental Development Index was 0.44 in non adoptive families, in which parents share nature as well as nurture with their offspring, as compared to 0.29 in adoptive families in which parents and offspring are genetically unrelated [@plomin1985c]. 

In twin studies, multivariate genetic analysis can be used to disentangle genetic and environmental effects from correlations between environmental measures and behavioral measures. @pike1996, found that two-thirds of the correlation between maternal negativity and adolescent children’s antisocial behavior could be attributed to genetic factors. More than a hundred studies have reported similar results, extending the findings to cross-lagged longitudinal analyses [@burt2005; @neiderhiser1999] and to new designs such as the children-of-twins design [@knopik2006; @mcadams2014] and the combined parents-of-twins and extended children-of-twins design [@narusyte2008].

GCTA is beginning to provide additional support for this finding. For example, bivariate GCTA has shown significant genetic mediation between family SES and children’s intelligence [@trzaskowski2014] and educational performance [@krapohl2015]. Showing genetic influence on family SES and its association with children’s intelligence and educational performance is less surprising than it might at first seem because family SES indexes parental education which also correlates substantially with parental intelligence.It is important to disentangle genetic and environmental influences on correlations between environmental and behavioral measures for three reasons. 

 - First, if these correlations are mediated genetically, interpretations that assume environmental causation are wrong, which has important implications for intervention. 

 - Second, genetically sensitive designs can identify causal effects of the environment free of genetic confound [@marceau2014]. 

 - Third, genetic mediation of the association between environmental measures and behavioral traits is not just a nuisance that needs to be controlled. It suggests a general way of thinking about how genotypes develop into phenotypes, from a passive model of imposed environments to an active model of shaped experiences in which we select, modify and create experiences in part based on our genetic propensities.

### 9- Most environmental effects aren’t shared by children raised in the same family

It is reasonable to think that growing up in the same family makes brothers and sisters similar psychologically, which is what developmental theorists from Freud onwards assumed. However, for most behavioral dimensions and disorders, it is genetics that accounts for similarity among siblings. Although environmental effects have a major impact, the salient environmental influences do not make siblings growing up in the same family similar. The message is not that family experiences are unimportant but rather that the relevant experiences are specific to each child in the family. This finding was ignored when it was first noted [@loehlin1976] and controversial when it was first highlighted [@plomin1987, @plomin1987b], but it is now widely accepted because it has consistently replicated [@plomin2011] This finding, that the effect of being raised in the same family is smaller than the effect of the genes is so consistent, it is described as the second law of behavioral genetics [@turkheimer2000]. 

The acceptance is so complete that the focus now is on finding **any** shared environmental influence [@buchannan2009], for example, 

 - personality [e.g., @matteson2013]

 - childhood psychopathology [@burt2009; @burt2013]

 - antisocial behavior in adolescence [@rhee2002]  ^[ shared environment accounts for about 15% of the total phenotypic variance; however, even here nonshared environment accounts for more of the variance, about 40% in meta-analyses, although these estimates include variance due to error of measurement]

 - academic achievement [@kovas2007] ^[ This trait consistently shows some shared environmental influence, presumably due to the effect of schools, although the effect is surprisingly modest in its magnitude (about 15% for English and 10% for Mathematics) given that this result is based on siblings growing up in the same family and being taught in the same school [@kovas2007]. @polderman2015 reports the shared environmental influence to be around 0.27.]

 - intelligence [@briley2013; @haworth2009] ^[ An interesting developmental exception is that shared environmental influence is found for intelligence up until adolescence and then diminishes as adolescents begin to make their own way in the world, as shown in meta-analyses [@briley2013; @haworth2009].]

Progress in identifying specific sources of nonshared environmental effects has been slow [@turkheimer2000b], although the MZ differences design is proving useful in detecting some nonshared effects controlling for genetic confounding [@plomin2011]. It seems likely that nonshared environmental effects are due to many experiences of small effect, analogous to Finding 3 ('heritability is caused by many genes of small effect'). That is, rather than asking whether a monolithic factor like parental control is primarily responsible for nonshared effects, it might be necessary to consider many seemingly inconsequential experiences that are tipping points in children’s lives. The ‘gloomy prospect’ is that these could be idiosyncratic stochastic experiences – chance [@plomin1987]. 

### 10- Abnormal is normal

A fundamental question about common psychological disorders is the extent to which genetic and environmental effects on disorders are merely the quantitative extremes of the same genetic and environmental factors that affect the rest of the distribution. Or are common disorders qualitatively different from the normal range of behavior? ^[ There are thousands of rare single-gene disorders such as phenylketonuria (PKU), which causes intellectual disability and has a frequency of about 1 in 10,000. This is the way we often think about disorders – as qualitatively different from the normal range of behavior. However, disorders studied by psychologists are much more common, including learning disabilities and psychopathology such as schizophrenia, autism, and hyperactivity.
]

The first quantitative genetic method is DeFries-Fulker (DF) extremes analysis, which assesses genetic links between the extremes and the normal range of variation by bringing together disorders and dimensions [@defries1985; @defries1988]. DF extremes analysis assesses the extent to which the quantitative scores of identical and fraternal twin partners (cotwins) of selected index cases (probands) regress differentially to the population mean. ^[ rather than assessing the genetic etiology of a disorder dichotomously using identical and fraternal twin concordance rates,  In other words, to the extent that genetic influences are responsible for the difference between the probands and the rest of the population, cotwins should be more similar to the probands for identical twins than for fraternal twins.] This comparison of identical and fraternal cotwin means yields an estimate of group heritability, an index of the extent to which the extreme scores of probands is due to genetic influences, and thereby provides a test of the hypothesis that the etiology of extreme scores differs from that of variation within the normal range. Consequently, finding significant group heritability implies that there are genetic links between the disorder, however assessed, and the quantitative trait. That is, if the measure of extremes (or a diagnosis) were not linked genetically to the quantitative trait, group heritability would be zero. DF extremes analysis was developed to assess reading disability in the context of reading ability [@defries1988]. Research using the method has consistently shown that group heritabilities are substantial for cognitive disability such as language, mathematical and general learning disability, as well as reading disability [@plomin2005]. An interesting exception involves severe intellectual disability (IQ < 70), which DF extremes analysis suggests is etiologically distinct from the normal distribution of intelligence [@reichenberg2016].

Another quantitative genetic technique, called liability-threshold model-fitting, relies on dichotomous data such as diagnoses. It assumes that liability is distributed normally but that the disorder occurs only when a certain threshold of liability is exceeded. Liability-threshold model-fitting estimates heritability of liability but this is not the heritability of the disorder as assessed quantitatively – it is the heritability of a hypothetical construct of continuous liability derived from dichotomous data. Nonetheless, if all the assumptions of the liability-threshold model are correct for a particular disorder, it will yield results similar to the DF extremes analysis to the extent that the quantitative dimension assessed underlies the qualitative disorder. For cognitive disabilities and abilities, liability-threshold analyses yield estimates of heritability similar to DF extremes analysis [@plomin2005]. Similar results from DF extremes analysis and liability-threshold model-fitting have been found for psychopathology [@charney2013; for recent examples, see @zavos2014]. In this way, these two quantitative genetic methods – DeFries-Fulker extremes analysis and liability-threshold model-fitting – lead to the conclusion that common disorders represent the extremes of the same genetic influences responsible for heritability throughout the distribution.

DNA research can address this issue directly: Genes associated with disorders are expected to be associated with dimensions and vice versa. Although evidence for replicable genetic associations is just emerging for complex traits, the data are consistent with this prediction [@plomin2009]. For example, a polygenic score derived from a GWA of ADHD cases and control significantly predicted an ADHD trait measure in the general population [@groenblokhuis; @martin2014] and vice versa [@stergiakouli2015].

Although the individual effects of genetic associations found in GCTA are tiny, their effects can be aggregated in ‘polygenic’ scores, like summing items on a test [@wray2014]. These polygenic scores are distributed normally, as Fisher anticipated [@fisher1919; @plomin2009]. The normal distribution of polygenic scores suggests that what we call disorders are the quantitative extreme of the same genetic factors that affect the rest of the distribution. Stated more provocatively, there are no common disorders, just quantitative traits – the abnormal is normal. This finding supports the recently adopted NIMH Research Domain Criteria strategy that focuses on dimensional models of psychopathology rather than diagnostic categories [@insel2010]^[ There is also a less obvious implication. Polygenic scores are typically referred to as polygenic risk scores because their constituent associations were derived from case-control studies comparing a group of individuals diagnosed with a disorder and controls. However, this ‘risk’ label misses the point that because these polygenic scores are distributed normally their distribution has a positive end as well as a negative end. This opens up opportunities for considering positive genetics -- how children flourish rather than flounder and about resilience rather than vulnerability [@plomin2009].
].

