# Heritability {.unnumbered}

_WARNING: This half-baked passion project has several sections with mass plagiarism and is subject to be incorrect. Please do not quote me on this stuff._

## Definitions

Heritability is a measure of how well differences in people’s genes account for differences in their traits… In scientific terms, heritability is a statistical concept (represented as h²) that describes how much of the variation in a given trait can be attributed to genetic variation. An estimate of the heritability of a trait is specific to one population in one environment, and it can change over time as circumstances change. Heritability estimates range from zero to one. A heritability close to zero indicates that almost all of the variability in a trait among people is due to environmental factors, with very little influence from genetic differences. [@MedlinePlus2021]

For a more quantitative breakdown, see the top respone on this blog post [here](https://biology.stackexchange.com/questions/42273/why-is-a-heritability-coefficient-not-an-index-of-how-genetic-something-is)

## What heritability does not mean
 -  Heritability does not indicate what proportion of a trait is determined by genes and what proportion is determined by environment. So, a heritability of 0.7 does not mean that a trait is 70% caused by genetic factors; it means that 70% of the variability in the trait in a population is due to genetic differences among people.
 -  Knowing the heritability of a trait does not necessarily provide information about which genes or environmental influences are involved, or how important they are in determining the trait.
 -  Heritable is not necessarily the same as familial. A trait is described as familial if it is shared by members of a family. Traits can appear in families for many reasons in addition to genetics, such as similarities in lifestyle and environment. For example, the language that is spoken tends to be shared in families, but it has no genetic contribution and so is not heritable.
 -  Heritability does not necessarily give any information about how easy or difficult it is to change a trait. For example, hair color is a trait with high heritability, but it is very easy to change with dye.

@tabery2009, @plato_stanford_heredity_2023

## Calculating Heritability

The tables below have been taken and abbreviated from @meyre2017

### Quantitative Genetic Family Based Studies

| Method of Assessing Heritability | Type of Participants | Statistical Methods |
|---|---|---|
| Classical twin study | Monozygotic and dizygotic twins | $H^2 = 2(r_{MZ} – r_{DZ})$ |
| Adopted twins reared apart | Monozygotic twins raised separately | $H^2 = r_{phenotype}/1$ |
| Family Studies | Different members of the same family | $h^2 = \frac{\text{intraclass correlation}}{\text{expected genetic relatedness}}$ |
| Structural Equation Modeling | Twin or family data | Estimates $h^2$ by creating linear regression models and maximizing the goodness-of-fit function between observed and predicted covariance matrices. |

### Molecular Genetic Population Based Studies

| Method of Assessing Heritability | Type of Participants | Statistical Methods |
|---|---|---|
| Genome-wide complex trait analyses | Data from unrelated individuals | Includes all SNPs simultaneously in regression model |
| Genome-wide association studies | Data from unrelated individuals | Regression between individual single nucleotide polymorphisms and the genotype of interest; Calculated by summing the variance in the phenotype explained by each individual SNP |

## How this booklet works

This booklet is compiled and heavily scraped and inspired from @sesardic2005. Credit goes to him for much of this content.
